use axum::{
    routing::{delete, get, post},
    Router,
};

use crate::state::AppState;

use super::handlers;

pub fn routes() -> Router<AppState> {
    Router::new()
        // Agency-side
        .route(
            "/api/agency/campaigns/:id",
            post(handlers::update_campaign_split),
        )
        // Brand billing analytics (implemented in campaigns)
        .route(
            "/api/brand/billing/spend",
            get(handlers::get_brand_spend_analytics),
        )
        .route(
            "/api/brand/billing/escrow-summary",
            get(handlers::get_brand_escrow_summary),
        )
        // Brand campaigns
        .route(
            "/api/brand/campaigns",
            post(handlers::create_campaign).get(handlers::list_campaigns),
        )
        .route(
            "/api/brand/campaigns/metrics",
            get(handlers::get_campaign_metrics),
        )
        .route("/api/brand/analytics", get(handlers::get_brand_analytics))
        .route(
            "/api/brand/activity-events",
            get(handlers::list_activity_events),
        )
        .route(
            "/api/brand/campaigns/:campaign_id",
            get(handlers::get_campaign).post(handlers::update_campaign),
        )
        .route(
            "/api/brand/campaigns/:campaign_id/mark-done",
            post(handlers::mark_campaign_done),
        )
        .route(
            "/api/brand/campaigns/:campaign_id/offer-options",
            get(handlers::list_offer_options),
        )
        .route(
            "/api/brand/campaigns/:campaign_id/offers",
            post(handlers::create_campaign_offers).get(handlers::list_campaign_offers),
        )
        .route(
            "/api/brand/docuseal/templates/upload",
            post(handlers::upload_campaign_contract_template),
        )
        // Offers
        .route(
            "/api/campaign-offers/:offer_id/respond",
            post(handlers::respond_to_campaign_offer),
        )
        .route(
            "/api/campaign-offers/my",
            get(handlers::list_my_campaign_offers),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts",
            post(handlers::create_offer_contract).get(handlers::list_offer_contracts),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/upload",
            post(handlers::upload_offer_contract),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/:contract_id/builder-token",
            get(handlers::get_offer_contract_builder_token),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/:contract_id",
            delete(handlers::delete_offer_contract),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/:contract_id/download",
            get(handlers::download_offer_contract_document),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/send",
            post(handlers::send_offer_contract),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/sync",
            post(handlers::sync_offer_contract),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/:contract_id/refresh",
            post(handlers::refresh_offer_contract_status),
        )
        .route(
            "/api/campaign-offers/:offer_id/contracts/:contract_id/archive",
            post(handlers::archive_offer_contract),
        )
        // Packages / inbox
        .route(
            "/api/campaign-offers/:offer_id/packages",
            post(handlers::create_offer_package),
        )
        .route(
            "/api/campaign-offers/:offer_id/packages/send",
            post(handlers::send_offer_package),
        )
        .route(
            "/api/brand/inbox/packages",
            get(handlers::list_brand_inbox_packages),
        )
        .route(
            "/api/campaign-offers/:offer_id/packages/:package_id/interactions",
            get(handlers::get_brand_package_interactions),
        )
        .route(
            "/api/campaign-offers/:offer_id/packages/brand-done",
            post(handlers::mark_brand_package_done),
        )
        .route(
            "/api/campaign-offers/:offer_id/packages/:package_id/dismiss",
            post(handlers::dismiss_brand_inbox_package),
        )
        .route(
            "/api/campaign-offers/:offer_id/packages/brand-delete",
            post(handlers::delete_brand_inbox_package),
        )
        .route(
            "/api/agency/brand-offers/package-feedback",
            get(handlers::list_agency_package_feedback),
        )
        .route(
            "/api/agency/brand-offers/packages",
            get(handlers::list_agency_offer_packages),
        )
        // Deliverables / asset requests
        .route(
            "/api/campaign-offers/:offer_id/deliverables",
            post(handlers::submit_offer_deliverable).get(handlers::list_offer_deliverables),
        )
        .route(
            "/api/campaign-offers/:offer_id/assignments",
            get(handlers::list_offer_talent_assignments),
        )
        .route(
            "/api/campaign-offers/:offer_id/asset-requests",
            get(handlers::list_offer_asset_requests).post(handlers::create_offer_asset_request),
        )
        .route(
            "/api/campaign-offers/:offer_id/asset-requests/upload",
            post(handlers::upload_offer_asset_request_file),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/upload",
            post(handlers::upload_offer_deliverable),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/upload-form",
            post(handlers::upload_offer_deliverable_form),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/submit",
            post(handlers::submit_draft_deliverables),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/:deliverable_id",
            delete(handlers::delete_offer_deliverable),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/:deliverable_id/file",
            get(handlers::serve_offer_deliverable),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/:deliverable_id/review",
            post(handlers::review_offer_deliverable),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/:deliverable_id/downloaded",
            post(handlers::mark_offer_deliverable_downloaded),
        )
        .route(
            "/api/campaign-offers/:offer_id/deliverables/:deliverable_id/comments",
            post(handlers::comment_offer_deliverable),
        )
        // Transfers / readiness
        .route(
            "/api/agency/campaign-offers/:offer_id/stripe-readiness",
            get(handlers::get_offer_stripe_readiness),
        )
        .route(
            "/api/agency/campaign-offers/:offer_id/transfer-status",
            get(handlers::get_offer_transfer_status),
        )
        .route(
            "/api/agency/campaign-offers/:offer_id/retry-transfers",
            post(handlers::retry_offer_transfers),
        )
        .route(
            "/api/talent/offer-asset-requests",
            get(handlers::list_creator_asset_requests),
        )
        .route(
            "/api/talent/offer-asset-requests/:request_id/viewed",
            post(handlers::mark_creator_asset_request_viewed),
        )
        .route(
            "/api/talent/campaign-offers/transfer-status",
            get(handlers::get_creator_transfer_status),
        )
        .route(
            "/api/talent/campaign-offers/:offer_id/retry-transfer",
            post(handlers::retry_creator_transfer),
        )
        // Webhooks (DocuSeal)
        .route(
            "/webhooks/docuseal/campaign-contracts",
            post(handlers::handle_campaign_contract_webhook),
        )
        .route(
            "/api/webhooks/brand-contracts",
            post(handlers::handle_webhook),
        )
}
