#!/usr/bin/env python3
import re
import sys

# Translation dictionaries
translations = {
    'es': {
        'Terms and Conditions': 'Términos y Condiciones',
        'Print / Save as PDF': 'Imprimir / Guardar como PDF',
        'Introduction and Acceptance of Terms': 'Introducción y Aceptación de los Términos',
        'Definitions': 'Definiciones',
        'Eligibility and Account Registration': 'Elegibilidad y Registro de Cuenta',
        'Platform Services': 'Servicios de la Plataforma',
        'Services for Agencies': 'Servicios para Agencias',
        'Services for Brands': 'Servicios para Marcas',
        'Service Availability': 'Disponibilidad del Servicio',
        'Subscription Plans, Fees, and Payment': 'Planes de Suscripción, Tarifas y Pago',
        'Subscription Plans': 'Planes de Suscripción',
        'Payment Terms': 'Términos de Pago',
        'Taxes': 'Impuestos',
        'Late Payment and Suspension': 'Pago Tardío y Suspensión',
        'Plan Changes': 'Cambios de Plan',
        'Likeness Licensing and Intellectual Property': 'Licencia de Imagen y Propiedad Intelectual',
        'License Grants': 'Concesión de Licencias',
        'Permitted Uses': 'Usos Permitidos',
        'Prohibited Uses': 'Usos Prohibidos',
        'Regulatory Compliance': 'Cumplimiento Regulatorio',
        "Likelee's Intellectual Property": 'Propiedad Intelectual de Likelee',
        'Data, Privacy, and Confidentiality': 'Datos, Privacidad y Confidencialidad',
        'Privacy Policy': 'Política de Privacidad',
        'Creator Data': 'Datos del Creador',
        'Brand Data': 'Datos de la Marca',
        'Confidentiality': 'Confidencialidad',
        'Representations and Warranties': 'Declaraciones y Garantías',
        'Agency Representations': 'Declaraciones de la Agencia',
        'Brand Representations': 'Declaraciones de la Marca',
        'Indemnification': 'Indemnización',
        'Limitation of Liability': 'Limitación de Responsabilidad',
        'Disclaimer of Warranties': 'Descargo de Garantías',
        'Term and Termination': 'Plazo y Terminación',
        'Dispute Resolution and Governing Law': 'Resolución de Disputas y Ley Aplicable',
        'Governing Law': 'Ley Aplicable',
        'Informal Resolution': 'Resolución Informal',
        'Arbitration': 'Arbitraje',
        'Class Action Waiver': 'Renuncia a Acción Colectiva',
        'Exception for Injunctive Relief': 'Excepción para Medidas Cautelares',
        'General Provisions': 'Disposiciones Generales',
        'Modifications to These Terms': 'Modificaciones a estos Términos',
        'Entire Agreement': 'Acuerdo Completo',
        'Severability': 'Divisibilidad',
        'Waiver': 'Renuncia',
        'Assignment': 'Cesión',
        'Force Majeure': 'Fuerza Mayor',
        'Notices': 'Notificaciones',
        'Questions? Contact us at': '¿Preguntas? Contáctenos en',
        'Empowering the Future of Likeness Licensing': 'Potenciando el Futuro de las Licencias de Imagen',
    },
    'fr': {
        'Terms and Conditions': 'Conditions Générales',
        'Print / Save as PDF': 'Imprimer / Enregistrer en PDF',
        'Introduction and Acceptance of Terms': 'Introduction et Acceptation des Conditions',
        'Definitions': 'Définitions',
        'Eligibility and Account Registration': 'Éligibilité et Inscription au Compte',
        'Platform Services': 'Services de la Plateforme',
        'Services for Agencies': 'Services pour les Agences',
        'Services for Brands': 'Services pour les Marques',
        'Service Availability': 'Disponibilité du Service',
        'Subscription Plans, Fees, and Payment': 'Plans d\'Abonnement, Frais et Paiement',
        'Subscription Plans': 'Plans d\'Abonnement',
        'Payment Terms': 'Conditions de Paiement',
        'Taxes': 'Taxes',
        'Late Payment and Suspension': 'Retard de Paiement et Suspension',
        'Plan Changes': 'Modifications du Plan',
        'Likeness Licensing and Intellectual Property': 'Licence d\'Image et Propriété Intellectuelle',
        'License Grants': 'Octroi de Licences',
        'Permitted Uses': 'Utilisations Autorisées',
        'Prohibited Uses': 'Utilisations Interdites',
        'Regulatory Compliance': 'Conformité Réglementaire',
        "Likelee's Intellectual Property": 'Propriété Intellectuelle de Likelee',
        'Data, Privacy, and Confidentiality': 'Données, Confidentialité et Vie Privée',
        'Privacy Policy': 'Politique de Confidentialité',
        'Creator Data': 'Données du Créateur',
        'Brand Data': 'Données de la Marque',
        'Confidentiality': 'Confidentialité',
        'Representations and Warranties': 'Déclarations et Garanties',
        'Agency Representations': 'Déclarations de l\'Agence',
        'Brand Representations': 'Déclarations de la Marque',
        'Indemnification': 'Indemnisation',
        'Limitation of Liability': 'Limitation de Responsabilité',
        'Disclaimer of Warranties': 'Exclusion de Garanties',
        'Term and Termination': 'Durée et Résiliation',
        'Dispute Resolution and Governing Law': 'Résolution des Litiges et Loi Applicable',
        'Governing Law': 'Loi Applicable',
        'Informal Resolution': 'Résolution Informelle',
        'Arbitration': 'Arbitrage',
        'Class Action Waiver': 'Renonciation aux Recours Collectifs',
        'Exception for Injunctive Relief': 'Exception pour Mesures Conservatoires',
        'General Provisions': 'Dispositions Générales',
        'Modifications to These Terms': 'Modifications de ces Conditions',
        'Entire Agreement': 'Accord Intégral',
        'Severability': 'Divisibilité',
        'Waiver': 'Renonciation',
        'Assignment': 'Cession',
        'Force Majeure': 'Force Majeure',
        'Notices': 'Notifications',
        'Questions? Contact us at': 'Des questions ? Contactez-nous à',
        'Empowering the Future of Likeness Licensing': 'Donner du Pouvoir à l\'Avenir des Licences d\'Image',
    },
    'de': {
        'Terms and Conditions': 'Allgemeine Geschäftsbedingungen',
        'Print / Save as PDF': 'Drucken / Als PDF speichern',
        'Introduction and Acceptance of Terms': 'Einführung und Annahme der Bedingungen',
        'Definitions': 'Definitionen',
        'Eligibility and Account Registration': 'Berechtigung und Kontoregistrierung',
        'Platform Services': 'Plattformdienste',
        'Services for Agencies': 'Dienste für Agenturen',
        'Services for Brands': 'Dienste für Marken',
        'Service Availability': 'Dienstverfügbarkeit',
        'Subscription Plans, Fees, and Payment': 'Abonnementpläne, Gebühren und Zahlung',
        'Subscription Plans': 'Abonnementpläne',
        'Payment Terms': 'Zahlungsbedingungen',
        'Taxes': 'Steuern',
        'Late Payment and Suspension': 'Verspätete Zahlung und Aussetzung',
        'Plan Changes': 'Planänderungen',
        'Likeness Licensing and Intellectual Property': 'Bildnislizenzierung und geistiges Eigentum',
        'License Grants': 'Lizenzgewährung',
        'Permitted Uses': 'Zulässige Verwendungen',
        'Prohibited Uses': 'Verbotene Verwendungen',
        'Regulatory Compliance': 'Einhaltung von Vorschriften',
        "Likelee's Intellectual Property": 'Geistiges Eigentum von Likelee',
        'Data, Privacy, and Confidentiality': 'Daten, Datenschutz und Vertraulichkeit',
        'Privacy Policy': 'Datenschutzrichtlinie',
        'Creator Data': 'Ersteller-Daten',
        'Brand Data': 'Markendaten',
        'Confidentiality': 'Vertraulichkeit',
        'Representations and Warranties': 'Zusicherungen und Garantien',
        'Agency Representations': 'Agentur-Zusicherungen',
        'Brand Representations': 'Marken-Zusicherungen',
        'Indemnification': 'Schadloshaltung',
        'Limitation of Liability': 'Haftungsbeschränkung',
        'Disclaimer of Warranties': 'Gewährleistungsausschluss',
        'Term and Termination': 'Laufzeit und Kündigung',
        'Dispute Resolution and Governing Law': 'Streitbeilegung und anwendbares Recht',
        'Governing Law': 'Anwendbares Recht',
        'Informal Resolution': 'Informelle Lösung',
        'Arbitration': 'Schiedsverfahren',
        'Class Action Waiver': 'Verzicht auf Sammelklagen',
        'Exception for Injunctive Relief': 'Ausnahme für einstweilige Verfügungen',
        'General Provisions': 'Allgemeine Bestimmungen',
        'Modifications to These Terms': 'Änderungen dieser Bedingungen',
        'Entire Agreement': 'Gesamtvereinbarung',
        'Severability': 'Salvatorische Klausel',
        'Waiver': 'Verzicht',
        'Assignment': 'Abtretung',
        'Force Majeure': 'Höhere Gewalt',
        'Notices': 'Mitteilungen',
        'Questions? Contact us at': 'Fragen? Kontaktieren Sie uns unter',
        'Empowering the Future of Likeness Licensing': 'Die Zukunft der Bildnislizenzierung gestalten',
    }
}

def translate_file(input_file, output_file, lang):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Update lang attribute
    content = content.replace('lang="en"', f'lang="{lang}"')
    
    # Translate text
    for english, translated in translations[lang].items():
        content = content.replace(english, translated)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Translated {input_file} to {output_file}")

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print("Usage: python translate_terms.py <input_file> <output_file> <lang>")
        sys.exit(1)
    
    translate_file(sys.argv[1], sys.argv[2], sys.argv[3])
