CREATE TABLE creator_custom_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  rate_type TEXT NOT NULL, -- 'content_type' or 'industry'
  rate_name TEXT NOT NULL,
  price_per_week_cents INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE(creator_id, rate_type, rate_name)
);

ALTER TABLE creator_custom_rates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Creators can view their own custom rates" 
ON creator_custom_rates FOR SELECT 
USING (auth.uid() = creator_id);

CREATE POLICY "Creators can insert their own custom rates" 
ON creator_custom_rates FOR INSERT 
WITH CHECK (auth.uid() = creator_id);

CREATE POLICY "Creators can update their own custom rates" 
ON creator_custom_rates FOR UPDATE 
USING (auth.uid() = creator_id);

CREATE POLICY "Creators can delete their own custom rates" 
ON creator_custom_rates FOR DELETE 
USING (auth.uid() = creator_id);

CREATE OR REPLACE FUNCTION upsert_creator_rates(p_creator_id UUID, p_rates JSONB)
RETURNS void AS $$
BEGIN
    -- Security check: ensure user can only update their own rates
    IF auth.uid() != p_creator_id THEN
        RAISE EXCEPTION 'Unauthorized: You can only update your own rates';
    END IF;

    -- First, delete all existing rates for this user
    DELETE FROM public.creator_custom_rates
    WHERE creator_id = p_creator_id;

    -- Then, insert the new ones from the JSONB array
    INSERT INTO public.creator_custom_rates (creator_id, rate_type, rate_name, price_per_week_cents)
    SELECT
        p_creator_id,
        (rate->>'rate_type')::TEXT,
        (rate->>'rate_name')::TEXT,
        (rate->>'price_per_week_cents')::INT
    FROM jsonb_array_elements(p_rates) AS rate;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
