-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agency_users (
                                     id uuid NOT NULL DEFAULT uuid_generate_v4(),
                                     agency_id uuid NOT NULL,
                                     user_id uuid NOT NULL,
                                     role text NOT NULL DEFAULT 'owner'::text,
                                     status text NOT NULL DEFAULT 'active'::text,
                                     created_at timestamp with time zone NOT NULL DEFAULT now(),
                                     CONSTRAINT agency_users_pkey PRIMARY KEY (id),
                                     CONSTRAINT agency_users_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.organization_profiles(id)
);
CREATE TABLE public.brand_licenses (
                                       id uuid NOT NULL DEFAULT gen_random_uuid(),
                                       brand_org_id uuid NOT NULL,
                                       face_user_id uuid NOT NULL,
                                       type text,
                                       status text NOT NULL DEFAULT 'active'::text,
                                       start_at timestamp with time zone,
                                       end_at timestamp with time zone,
                                       created_at timestamp with time zone NOT NULL DEFAULT now(),
                                       CONSTRAINT brand_licenses_pkey PRIMARY KEY (id),
                                       CONSTRAINT brand_licenses_brand_org_id_fkey FOREIGN KEY (brand_org_id) REFERENCES public.organization_profiles(id),
                                       CONSTRAINT brand_licenses_face_user_id_fkey FOREIGN KEY (face_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.brand_voice_assets (
                                           id uuid NOT NULL DEFAULT gen_random_uuid(),
                                           folder_id uuid NOT NULL,
                                           asset_type text NOT NULL,
                                           recording_id uuid,
                                           model_id uuid,
                                           storage_bucket text,
                                           storage_path text,
                                           public_url text,
                                           created_at timestamp with time zone NOT NULL DEFAULT now(),
                                           CONSTRAINT brand_voice_assets_pkey PRIMARY KEY (id),
                                           CONSTRAINT brand_voice_assets_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.brand_voice_folders(id),
                                           CONSTRAINT brand_voice_assets_recording_id_fkey FOREIGN KEY (recording_id) REFERENCES public.voice_recordings(id),
                                           CONSTRAINT brand_voice_assets_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.voice_models(id)
);
CREATE TABLE public.brand_voice_folders (
                                            id uuid NOT NULL DEFAULT gen_random_uuid(),
                                            brand_org_id uuid NOT NULL,
                                            face_user_id uuid NOT NULL,
                                            license_id uuid NOT NULL,
                                            name text NOT NULL,
                                            created_at timestamp with time zone NOT NULL DEFAULT now(),
                                            CONSTRAINT brand_voice_folders_pkey PRIMARY KEY (id),
                                            CONSTRAINT brand_voice_folders_brand_org_id_fkey FOREIGN KEY (brand_org_id) REFERENCES public.organization_profiles(id),
                                            CONSTRAINT brand_voice_folders_face_user_id_fkey FOREIGN KEY (face_user_id) REFERENCES public.profiles(id),
                                            CONSTRAINT brand_voice_folders_license_id_fkey FOREIGN KEY (license_id) REFERENCES public.brand_licenses(id)
);
CREATE TABLE public.creator_custom_rates (
                                             id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
                                             creator_id uuid NOT NULL,
                                             rate_type text NOT NULL,
                                             rate_name text NOT NULL,
                                             price_per_week_cents integer NOT NULL,
                                             created_at timestamp with time zone NOT NULL DEFAULT now(),
                                             updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                             CONSTRAINT creator_custom_rates_pkey PRIMARY KEY (id),
                                             CONSTRAINT creator_custom_rates_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.moderation_events (
                                          id uuid NOT NULL DEFAULT gen_random_uuid(),
                                          image_url text NOT NULL,
                                          user_id text,
                                          image_role text,
                                          flagged boolean NOT NULL DEFAULT false,
                                          labels jsonb NOT NULL DEFAULT '[]'::jsonb,
                                          review_status text NOT NULL DEFAULT 'pending'::text CHECK (review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
                                          reviewed_by text,
                                          reviewed_at timestamp with time zone,
                                          created_at timestamp with time zone NOT NULL DEFAULT now(),
                                          CONSTRAINT moderation_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organization_profiles (
                                              id uuid NOT NULL DEFAULT uuid_generate_v4(),
                                              owner_user_id uuid NOT NULL,
                                              email text NOT NULL,
                                              organization_name text NOT NULL,
                                              contact_name text,
                                              contact_title text,
                                              organization_type text,
                                              website text,
                                              phone_number text,
                                              industry text,
                                              primary_goal text,
                                              geographic_target text,
                                              production_type text,
                                              budget_range text,
                                              uses_ai text,
                                              creates_for text,
                                              roles_needed jsonb,
                                              client_count text,
                                              campaign_budget text,
                                              services_offered jsonb,
                                              handle_contracts text,
                                              talent_count text,
                                              licenses_likeness text,
                                              open_to_ai jsonb,
                                              campaign_types jsonb,
                                              bulk_onboard text,
                                              status text DEFAULT 'waitlist'::text,
                                              created_at timestamp with time zone NOT NULL DEFAULT now(),
                                              updated_at timestamp with time zone NOT NULL DEFAULT now(),
                                              CONSTRAINT organization_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
                                 id uuid NOT NULL DEFAULT gen_random_uuid(),
                                 email text,
                                 full_name text,
                                 creator_type text,
                                 city text,
                                 state text,
                                 birthdate date,
                                 bio text,
                                 gender text,
                                 content_types ARRAY,
                                 industries ARRAY,
                                 work_types ARRAY,
                                 brand_categories ARRAY,
                                 ethnicity ARRAY,
                                 vibes ARRAY,
                                 primary_platform text,
                                 platform_handle text,
                                 instagram_handle text,
                                 twitter_handle text,
                                 representation_status text,
                                 headshot_url text,
                                 sport text,
                                 athlete_type text,
                                 school_name text,
                                 age integer,
                                 languages text,
                                 kyc_status text DEFAULT 'not_started'::text CHECK (kyc_status = ANY (ARRAY['not_started'::text, 'pending'::text, 'approved'::text, 'rejected'::text])),
                                 liveness_status text DEFAULT 'not_started'::text CHECK (liveness_status = ANY (ARRAY['not_started'::text, 'pending'::text, 'approved'::text, 'rejected'::text])),
                                 kyc_provider text,
                                 kyc_session_id text,
                                 verified_at timestamp with time zone,
                                 visibility text DEFAULT 'private'::text,
                                 status text DEFAULT 'waitlist'::text,
                                 created_date timestamp with time zone DEFAULT now(),
                                 updated_date timestamp with time zone DEFAULT now(),
                                 created_by_id text,
                                 created_by text,
                                 is_sample boolean DEFAULT false,
                                 content_other text,
                                 avatar_canonical_url text,
                                 cameo_front_url text,
                                 cameo_left_url text,
                                 cameo_right_url text,
                                 created_at timestamp with time zone DEFAULT now(),
                                 updated_at timestamp with time zone,
                                 base_monthly_price_cents integer NOT NULL DEFAULT 15000 CHECK (base_monthly_price_cents >= 15000),
                                 currency_code text NOT NULL DEFAULT 'USD'::text CHECK (currency_code = 'USD'::text),
                                 pricing_updated_at timestamp with time zone DEFAULT now(),
                                 profile_photo_url text,
                                 accept_negotiations boolean DEFAULT false,
                                 content_restrictions ARRAY DEFAULT '{}'::text[],
                                 brand_exclusivity ARRAY DEFAULT '{}'::text[],
                                 CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reference_images (
                                         id uuid NOT NULL DEFAULT gen_random_uuid(),
                                         user_id uuid NOT NULL,
                                         section_id text NOT NULL,
                                         storage_bucket text NOT NULL,
                                         storage_path text NOT NULL,
                                         public_url text,
                                         width integer,
                                         height integer,
                                         size_bytes bigint,
                                         mime_type text,
                                         sha256 text,
                                         moderation_status text NOT NULL DEFAULT 'approved'::text,
                                         moderation_reason text,
                                         created_at timestamp with time zone NOT NULL DEFAULT now(),
                                         created_by uuid,
                                         CONSTRAINT reference_images_pkey PRIMARY KEY (id),
                                         CONSTRAINT reference_images_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.royalty_ledger (
                                       id uuid NOT NULL DEFAULT gen_random_uuid(),
                                       face_id uuid NOT NULL,
                                       booking_id text,
                                       brand_name text,
                                       amount_cents integer NOT NULL CHECK (amount_cents >= 0),
                                       currency_code text NOT NULL DEFAULT 'USD'::text CHECK (currency_code = 'USD'::text),
                                       status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text])),
                                       period_month date NOT NULL,
                                       created_at timestamp with time zone NOT NULL DEFAULT now(),
                                       CONSTRAINT royalty_ledger_pkey PRIMARY KEY (id),
                                       CONSTRAINT royalty_ledger_face_id_fkey FOREIGN KEY (face_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.voice_models (
                                     id uuid NOT NULL DEFAULT gen_random_uuid(),
                                     user_id uuid NOT NULL,
                                     provider text NOT NULL,
                                     provider_voice_id text NOT NULL,
                                     status text NOT NULL DEFAULT 'ready'::text,
                                     source_recording_id uuid,
                                     metadata jsonb,
                                     created_at timestamp with time zone NOT NULL DEFAULT now(),
                                     CONSTRAINT voice_models_pkey PRIMARY KEY (id),
                                     CONSTRAINT voice_models_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
                                     CONSTRAINT voice_models_source_recording_id_fkey FOREIGN KEY (source_recording_id) REFERENCES public.voice_recordings(id)
);
CREATE TABLE public.voice_recordings (
                                         id uuid NOT NULL DEFAULT gen_random_uuid(),
                                         user_id uuid NOT NULL,
                                         storage_bucket text NOT NULL,
                                         storage_path text NOT NULL,
                                         public_url text,
                                         duration_sec integer,
                                         mime_type text,
                                         emotion_tag text,
                                         accessible boolean NOT NULL DEFAULT true,
                                         created_at timestamp with time zone NOT NULL DEFAULT now(),
                                         CONSTRAINT voice_recordings_pkey PRIMARY KEY (id),
                                         CONSTRAINT voice_recordings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);