use crate::state::AppState;
use axum::http::header::{HeaderName, ACCEPT, AUTHORIZATION, CONTENT_TYPE};
use axum::{
    extract::DefaultBodyLimit,
    routing::{delete, get, patch, post, put},
    Router,
};
use tower_http::cors::{Any, CorsLayer};

pub fn build_router(state: AppState) -> Router {
    let cors = CorsLayer::new()
        .allow_origin(Any)
        .allow_methods(Any)
        .allow_headers([
            AUTHORIZATION,
            CONTENT_TYPE,
            ACCEPT,
            HeaderName::from_static("x-package-password"),
        ]);

    // Cache middleware layer - initializes L1 request cache
    let cache_layer = crate::cache::cache_layer;
    let idempotency_layer = crate::cache::idempotency_layer;

    let cache_idempotency = state.cache_idempotency.clone();
    let cache_metrics = state.cache_metrics.clone();

    Router::new()
        .route("/api/health", get(crate::health::health))
        // --- Admin Endpoints ---
        .route(
            "/api/admin/storage/backfill",
            post(crate::admin::backfill_storage),
        )
        .route(
            "/api/admin/storage/verify-parity",
            get(crate::admin::verify_storage_parity),
        )
        .route(
            "/api/admin/storage/brands",
            get(crate::admin::list_brands_storage),
        )
        .route(
            "/api/admin/storage/brands/:brand_id/quota",
            patch(crate::admin::update_brand_quota),
        )
        .route(
            "/api/admin/storage/analytics",
            get(crate::admin::get_platform_storage_analytics),
        )
        // --- Messaging Hub ---
        .route(
            "/api/conversations",
            get(crate::messaging::list_conversations),
        )
        .route(
            "/api/conversations/contacts",
            get(crate::messaging::list_contacts),
        )
        .route(
            "/api/conversations/start",
            post(crate::messaging::start_conversation),
        )
        .route(
            "/api/conversations/:id/messages",
            get(crate::messaging::list_messages),
        )
        .route("/api/messages/send", post(crate::messaging::send_message))
        .route(
            "/api/messages/:id",
            put(crate::messaging::edit_message).delete(crate::messaging::delete_message),
        )
        // --- Talent Portal ---
        .route("/api/talent/me", get(crate::talent::talent_me))
        .route("/api/talent/profile", post(crate::talent::update_profile))
        .route(
            "/api/talent/settings",
            get(crate::talent::get_portal_settings).post(crate::talent::update_portal_settings),
        )
        .route(
            "/api/talent/notifications",
            get(crate::talent::list_notifications),
        )
        .route(
            "/api/talent/notifications/:id/read",
            post(crate::talent::mark_notification_read),
        )
        .route(
            "/api/talent/agency-invites",
            get(crate::agencies::talent_invites::list_for_talent),
        )
        .route(
            "/api/creator/brand-connection-requests",
            get(crate::face_profiles::list_creator_brand_connection_requests),
        )
        .route(
            "/api/creator/brand-connection-requests/:id/accept",
            post(crate::face_profiles::accept_creator_brand_connection_request),
        )
        .route(
            "/api/creator/brand-connection-requests/:id/decline",
            post(crate::face_profiles::decline_creator_brand_connection_request),
        )
        .route(
            "/api/creator/brand-connections",
            get(crate::face_profiles::list_creator_brand_connections),
        )
        .route(
            "/api/creator/brand-connections/:brand_id/disconnect",
            post(crate::face_profiles::disconnect_creator_brand_connection),
        )
        .route(
            "/api/talent/licensing-requests",
            get(crate::talent::list_licensing_requests),
        )
        .route(
            "/api/talent/licensing-requests/:id/approve",
            post(crate::talent::approve_licensing_request),
        )
        .route(
            "/api/talent/licensing-requests/:id/decline",
            post(crate::talent::decline_licensing_request),
        )
        .route(
            "/api/talent/licenses",
            get(crate::talent::list_licenses_stub),
        )
        .route(
            "/api/talent/tax-documents/latest",
            get(crate::talent::get_latest_tax_document),
        )
        .route(
            "/api/talent/licensing/revenue",
            get(crate::talent::get_licensing_revenue),
        )
        .route(
            "/api/talent/licensing/earnings-by-campaign",
            get(crate::talent::get_earnings_by_campaign),
        )
        .route(
            "/api/talent/licensing/earnings-by-agency",
            get(crate::talent::get_earnings_by_agency),
        )
        .route("/api/talent/analytics", get(crate::talent::get_analytics))
        .route("/api/talent/bookings", get(crate::talent::list_bookings))
        .route(
            "/api/talent/book-outs",
            get(crate::talent::list_book_outs).post(crate::talent::create_book_out),
        )
        .route(
            "/api/talent/book-outs/:id",
            delete(crate::talent::delete_book_out),
        )
        .route(
            "/api/talent/booking-preferences",
            get(crate::talent::get_booking_preferences)
                .post(crate::talent::update_booking_preferences),
        )
        .route(
            "/api/talent/portfolio-items",
            get(crate::talent::list_portfolio_items).post(crate::talent::create_portfolio_item),
        )
        .route(
            "/api/talent/portfolio-items/:id",
            delete(crate::talent::delete_portfolio_item),
        )
        .route(
            "/api/talent/portfolio-items/upload",
            post(crate::talent::upload_portfolio_item),
        )
        .route(
            "/api/talent/irl/earnings/summary",
            get(crate::talent::get_irl_earnings_summary),
        )
        .route(
            "/api/talent/irl/earnings/payments",
            get(crate::talent::list_irl_payments),
        )
        .route(
            "/api/talent/irl/earnings/payout-request",
            post(crate::talent::create_irl_payout_request),
        )
        // --- Payouts (Stripe Connect) ---
        // Creator/Talent Payouts
        .route(
            "/api/payouts/onboarding_link",
            post(crate::billing::payouts::create_onboarding_link),
        )
        .route(
            "/api/payouts/account_status",
            get(crate::billing::payouts::get_account_status),
        )
        .route(
            "/api/payouts/balance",
            get(crate::billing::payouts::get_balance),
        )
        .route(
            "/api/payouts/request",
            post(crate::billing::payouts::request_payout),
        )
        .route(
            "/api/payouts/history",
            get(crate::billing::payouts::get_history),
        )
        // Talent-Specific Payouts (Portal variants)
        .route(
            "/api/talent/payouts/account-status",
            get(crate::billing::payouts::get_my_account_status),
        )
        .route(
            "/api/talent/payouts/onboarding-link",
            post(crate::billing::payouts::create_my_onboarding_link),
        )
        .route(
            "/api/talent/payouts/balance",
            get(crate::billing::payouts::get_my_balance),
        )
        .route(
            "/api/talent/payouts/request",
            post(crate::billing::payouts::request_my_payout),
        )
        // Agency Payouts
        .route(
            "/api/agency/payouts/onboarding_link",
            post(crate::billing::payouts::create_agency_onboarding_link),
        )
        .route(
            "/api/agency/payouts/account_status",
            get(crate::billing::payouts::get_agency_account_status),
        )
        .route(
            "/api/agency/payouts/balance",
            get(crate::billing::payouts::get_agency_balance),
        )
        .route(
            "/api/agency/payouts/request",
            post(crate::billing::payouts::request_agency_payout),
        )
        .route(
            "/api/agency/payouts/history",
            get(crate::billing::payouts::get_agency_payout_history),
        )
        // Agency Payout Settings & Schedule
        .route(
            "/api/agency/payout-settings",
            get(crate::agencies::get_payout_settings).post(crate::agencies::update_payout_settings),
        )
        .route(
            "/api/agency/payout-schedule/upcoming",
            get(crate::agencies::get_upcoming_payout_schedule),
        )
        // Creator Balance & Payout (New from main)
        .route(
            "/api/creator/balance",
            get(crate::billing::payment_links::get_creator_balance),
        )
        .route(
            "/api/creator/payout-request",
            post(crate::billing::payment_links::request_creator_payout),
        )
        .route(
            "/api/creator/payout-history",
            get(crate::billing::payment_links::get_creator_payout_history),
        )
        // --- Agency Dashboard & Features ---
        .route(
            "/api/agency/dashboard/overview",
            get(crate::agencies::dashboard::get_dashboard_overview),
        )
        .route(
            "/api/agency/dashboard/talent-performance",
            get(crate::agencies::dashboard::get_talent_performance),
        )
        .route(
            "/api/agency/dashboard/revenue-breakdown",
            get(crate::agencies::dashboard::get_revenue_breakdown),
        )
        .route(
            "/api/agency/dashboard/licensing-pipeline",
            get(crate::agencies::dashboard::get_licensing_pipeline),
        )
        .route(
            "/api/agency/dashboard/recent-activity",
            get(crate::agencies::dashboard::get_recent_activity),
        )
        .route(
            "/api/agency/dashboard/payment-history/top-earners",
            get(crate::agencies::dashboard::get_payment_history_top_earners),
        )
        .route(
            "/api/agency/dashboard/performance-tiers",
            get(crate::agencies::performance_tiers::get_performance_tiers),
        )
        .route(
            "/api/agency/dashboard/performance-tiers/configure",
            post(crate::agencies::performance_tiers::configure_performance_tiers),
        )
        .route(
            "/api/agency/dashboard/payout-weights",
            get(crate::agencies::performance_tiers::get_agency_payout_weights),
        )
        .route(
            "/api/agency/dashboard/talent-commissions/update",
            post(crate::agencies::performance_tiers::update_talent_commission),
        )
        .route(
            "/api/agency/dashboard/talent-commissions/bulk-update",
            post(crate::agencies::performance_tiers::bulk_update_talent_commissions),
        )
        .route(
            "/api/agency/dashboard/talent-commissions/history",
            get(crate::agencies::performance_tiers::get_commission_history),
        )
        .route(
            "/api/agency/analytics/dashboard",
            get(crate::analytics::get_analytics_dashboard),
        )
        .route(
            "/api/agency/analytics/roster",
            get(crate::analytics::get_roster_insights),
        )
        .route(
            "/api/agency/analytics/clients-campaigns",
            get(crate::analytics::get_clients_campaigns_analytics),
        )
        .route(
            "/api/agency/analytics/royalties",
            get(crate::analytics::get_royalties_payouts),
        )
        .route(
            "/api/agency/analytics/commission-breakdowns",
            get(crate::agencies::performance_tiers::get_commission_breakdowns),
        )
        .route(
            "/api/agency/analytics/expired-licenses",
            get(crate::analytics::get_expired_licenses),
        )
        .route(
            "/api/agency/roster",
            get(crate::agencies::roster::get_roster),
        )
        .route(
            "/api/agency/talent",
            post(crate::agencies::roster::create_talent),
        )
        .route(
            "/api/agency/talent/:id",
            post(crate::agencies::roster::update_talent),
        )
        .route(
            "/api/agency/talent/:id/campaigns",
            get(crate::agencies::roster::list_talent_campaigns),
        )
        .route(
            "/api/agency/talent-invites",
            get(crate::agencies::talent_invites::list_for_agency)
                .post(crate::agencies::talent_invites::create_for_agency),
        )
        .route(
            "/api/agency/talent-invites/:id/revoke",
            post(crate::agencies::talent_invites::revoke_for_agency),
        )
        .route("/api/team/context", get(crate::team::get_context))
        // --- Session Audit ---
        .route(
            "/api/auth/sessions",
            get(crate::sessions::list_sessions).delete(crate::sessions::revoke_all_other_sessions),
        )
        .route(
            "/api/auth/sessions/:session_id",
            delete(crate::sessions::revoke_session),
        )
        .route(
            "/api/auth/login-history",
            get(crate::sessions::get_login_history),
        )
        .route("/api/team/members", get(crate::team::list_members))
        .route("/api/team/audit-logs", get(crate::team::list_audit_logs))
        .route(
            "/api/team/invites",
            get(crate::team::list_invites).post(crate::team::create_invite),
        )
        .route(
            "/api/team/members/:user_id/role",
            post(crate::team::update_member_role),
        )
        .route(
            "/api/team/members/:user_id",
            axum::routing::delete(crate::team::remove_member),
        )
        .route(
            "/api/invites/team/:token",
            get(crate::team::get_invite_by_token),
        )
        .route(
            "/api/invites/team/:token/accept",
            post(crate::team::accept_invite_by_token),
        )
        .route(
            "/api/invites/team/:token/decline",
            post(crate::team::decline_invite_by_token),
        )
        .route(
            "/api/agency/licensing-requests",
            get(crate::licensing::requests::list_for_agency)
                .post(crate::licensing::requests::create),
        )
        .route(
            "/api/agency/licensing-requests/status",
            post(crate::licensing::requests::update_status_bulk),
        )
        .route(
            "/api/agency/licensing-requests/delete",
            post(crate::licensing::requests::delete_archived_requests),
        )
        .route(
            "/api/agency/licensing-requests/:id/send-payment-link",
            post(crate::licensing::requests::send_payment_link),
        )
        .route(
            "/api/agency/licensing-requests/pay-split",
            get(crate::licensing::requests::get_pay_split)
                .post(crate::licensing::requests::set_pay_split),
        )
        .route(
            "/api/agency/brand-license-requests",
            get(crate::brands::license_requests::list_for_agency),
        )
        .route(
            "/api/agency/brand-license-requests/status",
            post(crate::brands::license_requests::update_status_for_agency),
        )
        .route(
            "/api/agency/active-licenses",
            get(crate::licensing::active::list),
        )
        .route(
            "/api/agency/active-licenses/stats",
            get(crate::licensing::active::stats),
        )
        // Payment Links (for licensing)
        .route(
            "/api/agency/payment-links",
            get(crate::billing::payment_links::list_payment_links)
                .post(crate::billing::payment_links::generate_payment_link),
        )
        .route(
            "/api/agency/payment-links/:id",
            get(crate::billing::payment_links::get_payment_link)
                .post(crate::billing::payment_links::cancel_payment_link),
        )
        .route(
            "/api/agency/payment-links/send",
            post(crate::billing::payment_links::send_payment_link_email),
        )
        .route("/api/agency/talents", get(crate::agencies::list_talents))
        .route(
            "/api/agency/talents/:id/assets",
            get(crate::agencies::list_talent_assets),
        )
        .route(
            "/api/agency/talents/:id/assets/upload",
            post(crate::agencies::upload_talent_asset),
        )
        .route(
            "/api/agency/talents/:talent_id/assets/:asset_id",
            delete(crate::agencies::delete_talent_asset),
        )
        .route("/api/agency-register", post(crate::agencies::register))
        .route("/api/agency-profile", post(crate::agencies::update))
        .route(
            "/api/agency-profile/user",
            get(crate::agencies::get_profile),
        )
        .route(
            "/api/agency/clients",
            get(crate::agencies::list_clients).post(crate::agencies::create_client),
        )
        .route(
            "/api/agency/clients/:id",
            post(crate::agencies::update_client).delete(crate::agencies::delete_client),
        )
        .route(
            "/api/agency/clients/:id/contacts",
            get(crate::agencies::list_contacts).post(crate::agencies::create_contact),
        )
        .route(
            "/api/agency/clients/:client_id/contacts/:contact_id",
            delete(crate::agencies::delete_contact),
        )
        .route(
            "/api/agency/clients/:id/communications",
            get(crate::agencies::list_communications).post(crate::agencies::create_communication),
        )
        .route(
            "/api/agency/clients/:id/files",
            get(crate::agencies::list_client_files).post(crate::agencies::upload_client_file),
        )
        .route(
            "/api/agency/clients/:id/files/:file_id/signed-url",
            get(crate::agencies::get_client_file_signed_url),
        )
        .route(
            "/api/agency/files/upload",
            post(crate::agencies::upload_agency_file),
        )
        // Invoices, Expenses, Statements
        .route(
            "/api/invoices",
            get(crate::billing::invoices::list).post(crate::billing::invoices::create),
        )
        .route(
            "/api/invoices/:id",
            get(crate::billing::invoices::get).post(crate::billing::invoices::update),
        )
        .route(
            "/api/invoices/:id/mark-sent",
            post(crate::billing::invoices::mark_sent),
        )
        .route(
            "/api/invoices/:id/send-payment-reminder",
            post(crate::billing::invoices::send_payment_reminder),
        )
        .route(
            "/api/invoices/:id/mark-paid",
            post(crate::billing::invoices::mark_paid),
        )
        .route(
            "/api/invoices/:id/void",
            post(crate::billing::invoices::void_invoice),
        )
        .route(
            "/api/talent-statements",
            get(crate::billing::talent_statements::list),
        )
        .route(
            "/api/expenses",
            get(crate::billing::expenses::list).post(crate::billing::expenses::create),
        )
        // Digitals & Share
        .route(
            "/api/agency/digitals",
            get(crate::digitals::list_agency_digitals),
        )
        .route(
            "/api/agency/talent/:id/digitals",
            get(crate::digitals::list_talent_digitals).post(crate::digitals::create_talent_digital),
        )
        .route(
            "/api/agency/digitals/:id",
            post(crate::digitals::update_digital),
        )
        .route(
            "/api/agency/digitals/reminders",
            post(crate::digitals::send_digitals_reminders),
        )
        .route(
            "/api/agency/comp-cards/share",
            post(crate::agencies::clients::share_comp_card),
        )
        // --- License Management (Templates & Submissions) ---
        .route(
            "/api/license-templates",
            get(crate::licensing::templates::list).post(crate::licensing::templates::create),
        )
        .route(
            "/api/license-templates/stats",
            get(crate::licensing::templates::stats),
        )
        .route(
            "/api/license-templates/:id",
            post(crate::licensing::templates::update)
                .delete(crate::licensing::templates::delete_template),
        )
        .route(
            "/api/license-templates/:id/copy",
            post(crate::licensing::templates::copy),
        )
        .route(
            "/api/docuseal/builder-token",
            post(crate::licensing::templates::create_builder_token),
        )
        .route(
            "/api/license-submissions",
            get(crate::licensing::submissions::list).post(crate::licensing::submissions::create),
        )
        .route(
            "/api/marketplace/search",
            get(crate::face_profiles::search_marketplace_profiles),
        )
        .route(
            "/api/marketplace/:profile_type/:id/details",
            get(crate::face_profiles::get_marketplace_profile_details),
        )
        .route(
            "/api/marketplace/connect",
            post(crate::face_profiles::create_marketplace_connection_request),
        )
        .route(
            "/api/brand/connected-agencies",
            get(crate::face_profiles::list_brand_connected_agencies),
        )
        .route(
            "/api/brand/agency-connections/:agency_id/disconnect",
            post(crate::face_profiles::disconnect_brand_agency_connection_as_brand),
        )
        .route(
            "/api/brand/licensing-requests",
            get(crate::licensing::requests::list_for_brand)
                .post(crate::face_profiles::create_brand_licensing_request),
        )
        .route(
            "/api/brand/licensing-requests/status",
            post(crate::licensing::requests::update_status_for_brand),
        )
        .route(
            "/api/brand/licensing-requests/delete",
            post(crate::licensing::requests::delete_archived_requests_for_brand),
        )
        .route(
            "/api/brand/brand-license-requests",
            get(crate::brands::license_requests::list_for_brand)
                .post(crate::brands::license_requests::create),
        )
        .route(
            "/api/brand/agency-talent-rates",
            get(crate::face_profiles::list_brand_agency_talent_rates),
        )
        .route(
            "/api/agency/brand-connection-requests",
            get(crate::face_profiles::list_agency_brand_connection_requests),
        )
        .route(
            "/api/agency/brand-connections",
            get(crate::face_profiles::list_agency_brand_connections),
        )
        .route(
            "/api/agency/brand-connection-requests/:id/accept",
            post(crate::face_profiles::accept_agency_brand_connection_request),
        )
        .route(
            "/api/agency/brand-connection-requests/:id/decline",
            post(crate::face_profiles::decline_agency_brand_connection_request),
        )
        .route(
            "/api/agency/brand-connections/:brand_id/disconnect",
            post(crate::face_profiles::disconnect_brand_agency_connection_as_agency),
        )
        .route(
            "/api/license-submissions/draft",
            post(crate::licensing::submissions::create_draft),
        )
        .route(
            "/api/license-submissions/create-and-send",
            post(crate::licensing::submissions::create_and_send),
        )
        .route(
            "/api/license-submissions/:id/finalize",
            post(crate::licensing::submissions::finalize),
        )
        .route(
            "/api/license-submissions/:id/preview",
            post(crate::licensing::submissions::preview),
        )
        .route(
            "/api/license-submissions/:id",
            get(crate::licensing::submissions::get).delete(crate::licensing::submissions::archive),
        )
        .route(
            "/api/license-submissions/:id/resend",
            post(crate::licensing::submissions::resend),
        )
        .route(
            "/api/license-submissions/:id/sync-status",
            post(crate::licensing::submissions::sync_status),
        )
        // --- Storage (S3 / Supabase) ---
        .route(
            "/api/agency/storage/usage",
            get(crate::agencies::get_agency_storage_usage),
        )
        .route(
            "/api/agency/storage/folders",
            get(crate::agencies::list_agency_folders).post(crate::agencies::create_agency_folder),
        )
        .route(
            "/api/agency/storage/folders/:folder_id",
            delete(crate::agencies::delete_agency_folder)
                .patch(crate::agencies::update_agency_folder)
                .put(crate::agencies::update_agency_folder),
        )
        .route(
            "/api/agency/storage/files",
            get(crate::agencies::list_agency_files),
        )
        .route(
            "/api/agency/storage/files/upload",
            post(crate::agencies::upload_agency_storage_file),
        )
        .route(
            "/api/agency/storage/files/:file_id",
            delete(crate::agencies::delete_agency_storage_file),
        )
        .route(
            "/api/agency/storage/files/:file_id/signed-url",
            get(crate::agencies::get_agency_storage_file_signed_url),
        )
        // --- Unified Org Storage ---
        .route(
            "/api/org/storage/assets",
            get(crate::storage::org_storage::list_org_storage_assets),
        )
        .route(
            "/api/org/storage/files/save-from-url",
            post(crate::storage::org_storage::save_from_url),
        )
        // --- Talent Packages ---
        .route(
            "/api/agency/packages",
            get(crate::packages::list_packages).post(crate::packages::create_package),
        )
        .route(
            "/api/agency/packages/stats",
            get(crate::packages::get_dashboard_stats),
        )
        .route(
            "/api/agency/packages/:id",
            get(crate::packages::get_package)
                .delete(crate::packages::delete_package)
                .put(crate::packages::update_package),
        )
        .route(
            "/api/public/packages/:token",
            get(crate::packages::get_public_package),
        )
        // Catalogs
        .route(
            "/api/agency/catalogs",
            get(crate::catalogs::list_catalogs).post(crate::catalogs::create_catalog),
        )
        .route(
            "/api/agency/catalogs/eligible-requests",
            get(crate::catalogs::list_eligible_requests),
        )
        .route(
            "/api/agency/catalogs/:id",
            delete(crate::catalogs::delete_catalog),
        )
        .route(
            "/api/public/catalogs/:token",
            get(crate::catalogs::get_public_catalog),
        )
        .route(
            "/api/public/packages/:token/full-assets-request",
            post(crate::packages::create_public_package_full_assets_request),
        )
        .route(
            "/api/public/packages/:token/interactions",
            post(crate::packages::create_interaction).delete(crate::packages::delete_interaction),
        )
        // --- Scouting ---
        .route(
            "/api/scouting/templates",
            get(crate::scouting::list_templates).post(crate::scouting::create_template),
        )
        .route(
            "/api/scouting/templates/sync",
            post(crate::scouting::sync_templates),
        )
        .route(
            "/api/scouting/templates/upload",
            post(crate::scouting::create_template_from_pdf),
        )
        .route(
            "/api/scouting/templates/:id",
            delete(crate::scouting::delete_template).put(crate::scouting::update_template_from_pdf),
        )
        .route(
            "/api/scouting/offers",
            get(crate::scouting::list_offers).post(crate::scouting::create_offer),
        )
        .route(
            "/api/scouting/offers/:offer_id",
            get(crate::scouting::get_offer_details).delete(crate::scouting::delete_offer),
        )
        .route(
            "/api/scouting/offers/refresh-status",
            post(crate::scouting::refresh_offer_status),
        )
        .route("/api/scouting/geocode", get(crate::scouting::geocode))
        .route(
            "/api/scouting/builder-token",
            post(crate::scouting::create_builder_token),
        )
        // --- Bookings & Availability ---
        .route(
            "/api/bookings",
            get(crate::bookings::list).post(crate::bookings::create),
        )
        .route(
            "/api/booking/calendly-url",
            get(crate::bookings::calendly::get_calendly_booking_url),
        )
        .route(
            "/api/calendly/settings",
            get(crate::bookings::calendly::get_agency_calendly_settings)
                .post(crate::bookings::calendly::update_agency_calendly_settings),
        )
        .route(
            "/api/calendly/event-types",
            get(crate::bookings::calendly::get_calendly_event_types),
        )
        .route(
            "/api/bookings/with-files",
            post(crate::bookings::create_with_files),
        )
        .route(
            "/api/bookings-campaigns",
            get(crate::bookings::campaigns::list).post(crate::bookings::campaigns::create),
        )
        .route(
            "/api/bookings-campaigns/:id",
            post(crate::bookings::campaigns::update)
                .delete(crate::bookings::campaigns::delete_campaign),
        )
        .route(
            "/api/bookings-campaigns/:campaign_id/deliverables",
            get(crate::bookings::deliverables::list_deliverables)
                .post(crate::bookings::deliverables::upload_deliverable),
        )
        .route(
            "/api/bookings-campaigns/:campaign_id/deliverables/submit",
            post(crate::bookings::deliverables::submit_deliverables),
        )
        .route(
            "/api/bookings-campaigns/:campaign_id/deliverables/submit-to-brand",
            post(crate::bookings::deliverables::submit_to_brand),
        )
        .route(
            "/api/bookings-campaigns/:campaign_id/deliverables/:deliverable_id/review",
            post(crate::bookings::deliverables::review_deliverable),
        )
        .route(
            "/api/bookings-campaigns/:campaign_id/deliverables/:deliverable_id",
            delete(crate::bookings::deliverables::delete_deliverable),
        )
        .route(
            "/api/bookings-campaigns/:campaign_id/deliverables/:deliverable_id/file",
            get(crate::bookings::deliverables::serve_deliverable_file),
        )
        .route("/api/bookings/:id", post(crate::bookings::update))
        .route(
            "/api/bookings/:id/files/upload",
            post(crate::bookings::upload_booking_file),
        )
        .route(
            "/api/bookings/:id/files/:file_id",
            get(crate::bookings::serve_booking_file),
        )
        .route("/api/bookings/:id/cancel", post(crate::bookings::cancel))
        .route(
            "/api/book-outs",
            get(crate::bookings::book_outs::list).post(crate::bookings::book_outs::create),
        )
        .route(
            "/api/book-outs/:id",
            delete(crate::bookings::book_outs::delete_book_out),
        )
        // --- Brands & Marketing ---
        .route("/api/brand-register", post(crate::brands::register))
        .route("/api/brand-profile", post(crate::brands::update))
        .route("/api/brand-profile/user", get(crate::brands::get_by_user))
        // --- Brand Notifications ---
        .route(
            "/api/brand/notifications",
            get(crate::brands::list_notifications),
        )
        .route(
            "/api/brand/notifications/count",
            get(crate::brands::get_notification_count),
        )
        .route(
            "/api/brand/notifications/:id/read",
            post(crate::brands::mark_notification_read),
        )
        // --- Brand Badge Counts ---
        .route(
            "/api/brand/inbox/unread-count",
            get(crate::brands::get_inbox_unread_count),
        )
        .route(
            "/api/brand/inbox/mark-viewed",
            post(crate::brands::mark_inbox_packages_viewed),
        )
        .route(
            "/api/brand/jobs/unread-count",
            get(crate::brands::get_jobs_unread_count),
        )
        .route(
            "/api/brand/jobs/mark-viewed",
            post(crate::brands::mark_job_applications_viewed),
        )
        .route(
            "/api/brand/licensing/contracts-count",
            get(crate::brands::get_licensing_contracts_count),
        )
        .route(
            "/api/brand/billing/checkout",
            post(crate::billing::create_brand_subscription_checkout),
        )
        .route(
            "/api/brand/billing/portal",
            post(crate::billing::create_brand_billing_portal),
        )
        .route(
            "/api/brand/billing/studio-addon/checkout",
            post(crate::billing::create_brand_studio_addon_checkout),
        )
        .route(
            "/api/brand/billing/studio-addon/verify",
            post(crate::billing::verify_brand_studio_addon_checkout),
        )
        .route(
            "/api/brand/billing/payment-method/setup-intent",
            post(crate::billing::create_brand_payment_method_setup_intent),
        )
        .route(
            "/api/brand/billing/stripe-config",
            get(crate::billing::get_stripe_publishable_key),
        )
        .route(
            "/api/brand/billing/payment-methods",
            get(crate::billing::get_brand_payment_methods),
        )
        .route(
            "/api/brand/billing/payment-method/set-primary",
            post(crate::billing::set_brand_primary_payment_method),
        )
        .route(
            "/api/brand/billing/payment-method/delete",
            post(crate::billing::delete_brand_payment_method),
        )
        .route(
            "/api/brand/billing/status",
            get(crate::billing::get_brand_billing_status),
        )
        .route(
            "/api/brand/billing/invoices",
            get(crate::billing::list_brand_invoices),
        )
        .route(
            "/api/brand/billing/budget-settings",
            get(crate::billing::get_brand_budget_settings)
                .put(crate::billing::update_brand_budget_settings),
        )
        .route(
            "/api/cron/budget-alerts",
            post(crate::billing::check_budget_alerts_cron),
        )
        .route(
            "/api/cron/reset-monthly-budget-alerts",
            post(crate::billing::reset_monthly_budget_alerts),
        )
        .route(
            "/api/cron/license-expiration-alerts",
            post(crate::billing::check_license_expiration_alerts_cron),
        )
        .route(
            "/api/cron/auto-archive-licensing-requests",
            post(crate::billing::auto_archive_expired_licensing_requests_cron),
        )
        .merge(crate::campaigns::routes())
        .route(
            "/api/brand/campaign-offers/:id/checkout",
            post(crate::billing::create_campaign_offer_checkout),
        )
        .route(
            "/api/brand/campaigns/:campaign_id/license-requests",
            post(crate::licensing::requests::create_for_brand_campaign),
        )
        .route(
            "/api/brand/campaigns/:campaign_id/license-requests/options",
            get(crate::licensing::requests::list_brand_campaign_license_options),
        )
        .route(
            "/api/jobs",
            post(crate::jobs::create_job).get(crate::jobs::list_jobs),
        )
        .route("/api/jobs/:job_id", put(crate::jobs::update_job))
        .route("/api/jobs/my", get(crate::jobs::list_my_jobs))
        .route("/api/jobs/:job_id/apply", post(crate::jobs::apply_job))
        .route(
            "/api/jobs/:job_id/decline",
            post(crate::jobs::decline_job_invite),
        )
        .route(
            "/api/jobs/:job_id/accept",
            post(crate::jobs::accept_job_invite),
        )
        .route(
            "/api/jobs/:job_id/applications",
            get(crate::jobs::list_job_applications),
        )
        .route(
            "/api/brand/voice-folders",
            get(crate::licensing::licenses::list_brand_voice_folders),
        )
        .route(
            "/api/brand/voice-assets",
            get(crate::licensing::licenses::list_brand_voice_assets),
        )
        .nest("/api/brand/storage", crate::brands::storage::routes())
        .route(
            "/api/creator-rates",
            get(crate::creator_rates::get_creator_rates)
                .post(crate::creator_rates::upsert_creator_rates),
        )
        // --- KYC ---
        .route("/api/kyc/session", post(crate::kyc::create_session))
        .route("/api/kyc/status", get(crate::kyc::get_status))
        .route(
            "/api/kyc/organization/session",
            post(crate::kyc::create_session),
        )
        .route("/api/kyc/organization/status", get(crate::kyc::get_status))
        // --- Creators, Faces, Moderation ---
        .route(
            "/api/dashboard",
            get(crate::creators::dashboard::get_dashboard),
        ) // Common dashboard
        .route("/api/profile", post(crate::creators::upsert_profile))
        .route(
            "/api/profile/photo-upload",
            post(crate::creators::upload_profile_photo),
        )
        .route(
            "/api/face-profiles",
            post(crate::face_profiles::create_face_profile),
        )
        .route(
            "/api/face-profiles/:id",
            post(crate::face_profiles::update_face_profile),
        )
        .route("/api/faces/search", get(crate::face_profiles::search_faces))
        .route("/api/email/available", get(crate::creators::check_email))
        .route(
            "/api/reference-images/upload",
            post(crate::reference_images::upload_reference_image),
        )
        .route(
            "/api/reference-images",
            get(crate::reference_images::list_reference_images),
        )
        .route(
            "/api/reference-images/:section_id",
            delete(crate::reference_images::delete_reference_image),
        )
        // --- Voice ---
        .route(
            "/api/voice/recordings",
            get(crate::kyc::voice::list_voice_recordings)
                .post(crate::kyc::voice::upload_voice_recording),
        )
        .route(
            "/api/voice/recordings/signed-url",
            get(crate::kyc::voice::signed_url_for_recording),
        )
        .route(
            "/api/voice/recordings/:id",
            delete(crate::kyc::voice::delete_voice_recording),
        )
        .route(
            "/api/voice/models",
            post(crate::kyc::voice::register_voice_model),
        )
        .route(
            "/api/voice/models/clone",
            post(crate::kyc::voice::create_clone_from_recording),
        )
        // --- Connections & Invites ---
        .route(
            "/api/creator/agency-invites",
            get(crate::creator_agency_connection::list_invites),
        )
        .route(
            "/api/creator/agency-invites/:id/accept",
            post(crate::creator_agency_connection::accept_invite),
        )
        .route(
            "/api/creator/agency-invites/:id/decline",
            post(crate::creator_agency_connection::decline_invite),
        )
        .route(
            "/api/creator/agency-connections",
            get(crate::creator_agency_connection::list_connections),
        )
        .route(
            "/api/creator/agency-connections/:agency_id/disconnect",
            post(crate::creator_agency_connection::disconnect_agency),
        )
        .route(
            "/api/agency/creator-connections/:creator_id/disconnect/approve",
            post(crate::creator_agency_connection::approve_disconnect_request),
        )
        .route(
            "/api/agency/creator-connections/:creator_id/disconnect/reject",
            post(crate::creator_agency_connection::reject_disconnect_request),
        )
        .route(
            "/api/agency/creator-connections/:creator_id/contract",
            get(crate::creator_agency_connection::get_agency_contract_summary),
        )
        .route(
            "/api/marketplace/contracts/:id/sync",
            post(crate::agencies::marketplace_contracts::sync_contract_endpoint),
        )
        .route(
            "/api/marketplace/contracts/:id/finalize",
            post(crate::agencies::marketplace_contracts::finalize_contract_endpoint),
        )
        .route(
            "/api/invites/agency-talent/:token",
            get(crate::agencies::talent_invites::get_by_token),
        )
        .route(
            "/api/invites/agency-talent/:token/accept",
            post(crate::agencies::talent_invites::accept_by_token),
        )
        .route(
            "/api/invites/agency-talent/:token/decline",
            post(crate::agencies::talent_invites::decline_by_token),
        )
        .route(
            "/api/invites/agency-talent/:token/magic-link",
            get(crate::agencies::talent_invites::get_magic_link_by_token),
        )
        // --- Studio (AI Generation) ---
        .route("/api/studio/generate", post(crate::studio::generate))
        .route("/api/studio/jobs/:id", get(crate::studio::job_status))
        .route("/api/studio/wallet", get(crate::studio::get_wallet))
        .route(
            "/api/studio/generations",
            get(crate::studio::list_generations),
        )
        .route(
            "/api/studio/transactions",
            get(crate::studio::list_transactions),
        )
        .route("/api/studio/presets", get(crate::studio::list_presets))
        .route(
            "/api/studio/campaigns/:campaign_id/generations",
            get(crate::studio::list_campaign_generations),
        )
        .route("/api/studio/upload", post(crate::studio::upload_file))
        .route(
            "/api/studio/licensed-assets",
            get(crate::studio::list_licensed_assets),
        )
        .route(
            "/api/studio/generations/:generation_id/save-to-storage",
            post(crate::studio::save_generation_to_storage),
        )
        // --- Legacy Stripe endpoint used by some UI flows ---
        .route(
            "/stripe/create-checkout-session",
            post(crate::billing::create_checkout_session_legacy),
        )
        .route(
            "/api/stripe/create-checkout-session",
            post(crate::billing::create_checkout_session_legacy),
        )
        // --- Webhooks ---
        .route(
            "/webhooks/stripe",
            post(crate::billing::payouts::stripe_webhook),
        )
        .route("/webhooks/kyc/veriff", post(crate::kyc::veriff_webhook))
        .route(
            "/webhooks/calendly",
            post(crate::bookings::calendly::handle_calendly_webhook),
        )
        .route("/webhooks/docuseal", post(crate::scouting::handle_webhook))
        .route(
            "/webhooks/docuseal/marketplace-contracts",
            post(crate::agencies::marketplace_contracts::handle_webhook),
        )
        .route(
            "/api/webhooks/licenseContract",
            post(crate::licensing::submissions::handle_webhook),
        )
        // --- Instagram Scraper (Apify) ---
        .route(
            "/api/instagram/scrape",
            post(crate::services::instagram_scraper::scrape_instagram_profile)
                .get(crate::services::instagram_scraper::scrape_instagram_profile_query),
        )
        .route(
            "/api/instagram/webhook",
            post(crate::services::instagram_scraper::handle_apify_webhook),
        )
        // --- Integrations & Misc ---
        .route(
            "/api/integrations/core/send-email",
            post(crate::email::send_email),
        )
        .route(
            "/api/integrations/core/send-sales-inquiry",
            post(crate::email::send_sales_inquiry),
        )
        .route(
            "/api/agency/billing/checkout",
            post(crate::billing::create_agency_subscription_checkout),
        )
        .route(
            "/api/creator/billing/checkout",
            post(crate::billing::create_creator_subscription_checkout),
        )
        .route(
            "/api/creator/billing/upgrade",
            post(crate::billing::upgrade_creator_subscription),
        )
        .route(
            "/api/creator/billing/status",
            get(crate::billing::get_creator_billing_status),
        )
        .route(
            "/api/creator/billing/portal",
            post(crate::billing::create_creator_billing_portal),
        )
        .route(
            "/api/agency/billing/change-plan",
            post(crate::billing::change_agency_subscription_plan),
        )
        .route(
            "/api/agency/billing/checkout/sync",
            post(crate::billing::sync_agency_checkout_session),
        )
        .route(
            "/api/agency/billing/addons/irl-booking/checkout",
            post(crate::billing::create_agency_irl_booking_addon_checkout),
        )
        .route(
            "/api/agency/billing/addons/studio/checkout",
            post(crate::billing::create_agency_studio_addon_checkout),
        )
        .route(
            "/api/agency/billing/addons/seats",
            post(crate::billing::create_or_update_agency_seat_addon),
        )
        .route(
            "/api/agency/billing/addons/seats/breakdown",
            get(crate::billing::get_agency_seat_breakdown),
        )
        .route(
            "/api/agency/billing/start-trial",
            post(crate::billing::start_agency_pro_trial),
        )
        .route(
            "/api/agency/billing/status",
            get(crate::billing::get_agency_billing_status),
        )
        .route(
            "/api/agency/billing/portal",
            post(crate::billing::create_agency_billing_portal),
        )
        .route(
            "/api/licenses/activated",
            post(crate::licensing::licenses::activated_stub),
        )
        .route(
            "/api/notifications/booking-created-email",
            post(crate::notifications::booking_created_email),
        )
        .route(
            "/api/notifications/booking-notifications",
            get(crate::notifications::list_booking_notifications),
        )
        .with_state(state)
        .layer(DefaultBodyLimit::max(500 * 1024 * 1024)) // 500MB limit
        .layer(cors)
        .layer(axum::middleware::from_fn(idempotency_layer))
        .layer(axum::middleware::from_fn(cache_layer))
        .layer(axum::Extension(cache_metrics))
        .layer(axum::Extension(cache_idempotency))
}
