#![allow(clippy::uninlined_format_args)]

pub mod admin;
pub mod agency;
pub mod auth;
pub mod billing;
pub mod booking;
pub mod brand;
pub mod cache;
pub mod config;
pub mod creator;
pub mod errors;
pub mod health;
pub mod jobs;
pub mod kyc;
pub mod licensing;
pub mod liveness;
pub mod messaging;
pub mod payouts;
pub mod router;
pub mod scouting;
pub mod services;
pub mod sessions;
pub mod storage;
pub mod studio;
pub mod talent;
pub mod team;
pub mod utils;
pub mod voice;
