use crate::config::AppState;
use axum::{
    extract::DefaultBodyLimit,
    routing::{delete, get, post},
    Router,
};
use tower_http::cors::{Any, CorsLayer};

pub fn build_router(state: AppState) -> Router {
    let cors = CorsLayer::new()
        .allow_origin(Any)
        .allow_methods(Any)
        .allow_headers(Any);
    Router::new()
        .route("/api/health", get(crate::health::health))
        .route("/api/talent/me", get(crate::talent::talent_me))
        .route(
            "/api/talent/settings",
            get(crate::talent::get_portal_settings).post(crate::talent::update_portal_settings),
        )
        .route(
            "/api/talent/agency-invites",
            get(crate::agency_talent_invites::list_for_talent),
        )
        .route(
            "/api/talent/licensing-requests",
            get(crate::talent::list_licensing_requests),
        )
        .route(
            "/api/talent/licensing-requests/:id/approve",
            post(crate::talent::approve_licensing_request),
        )
        .route(
            "/api/talent/licensing-requests/:id/decline",
            post(crate::talent::decline_licensing_request),
        )
        .route(
            "/api/talent/licenses",
            get(crate::talent::list_licenses_stub),
        )
        .route(
            "/api/talent/tax-documents/latest",
            get(crate::talent::get_latest_tax_document),
        )
        .route(
            "/api/talent/licensing/revenue",
            get(crate::talent::get_licensing_revenue),
        )
        .route(
            "/api/talent/licensing/earnings-by-campaign",
            get(crate::talent::get_earnings_by_campaign),
        )
        .route(
            "/api/talent/licensing/earnings-by-agency",
            get(crate::talent::get_earnings_by_agency),
        )
        .route(
            "/api/talent/payouts/balance",
            get(crate::payouts::get_my_balance),
        )
        .route(
            "/api/talent/payouts/request",
            post(crate::payouts::request_my_payout),
        )
        .route("/api/talent/analytics", get(crate::talent::get_analytics))
        .route(
            "/api/talent/portfolio-items",
            get(crate::talent::list_portfolio_items).post(crate::talent::create_portfolio_item),
        )
        .route(
            "/api/talent/portfolio-items/:id",
            delete(crate::talent::delete_portfolio_item),
        )
        .route(
            "/api/talent/notifications",
            get(crate::talent::list_notifications),
        )
        .route(
            "/api/talent/notifications/:id/read",
            post(crate::talent::mark_notification_read),
        )
        .route(
            "/api/talent/payouts/account-status",
            get(crate::payouts::get_my_account_status),
        )
        .route(
            "/api/talent/payouts/onboarding-link",
            get(crate::payouts::create_my_onboarding_link),
        )
        .route(
            "/api/creator/agency-connections",
            get(crate::creator_agency_connection::list_connections),
        )
        .route(
            "/api/creator/agency-connections/:agency_id/disconnect",
            post(crate::creator_agency_connection::disconnect_agency),
        )
        .route("/api/talent/profile", post(crate::talent::update_profile))
        .route("/api/talent/bookings", get(crate::talent::list_bookings))
        .route(
            "/api/talent/book-outs",
            get(crate::talent::list_book_outs).post(crate::talent::create_book_out),
        )
        .route(
            "/api/talent/book-outs/:id",
            delete(crate::talent::delete_book_out),
        )
        .route(
            "/api/talent/booking-preferences",
            get(crate::talent::get_booking_preferences)
                .post(crate::talent::update_booking_preferences),
        )
        .route(
            "/api/talent/irl/earnings/summary",
            get(crate::talent::get_irl_earnings_summary),
        )
        .route(
            "/api/talent/irl/earnings/payments",
            get(crate::talent::list_irl_payments),
        )
        .route(
            "/api/talent/irl/earnings/payout-request",
            post(crate::talent::create_irl_payout_request),
        )
        .route(
            "/api/talent/portfolio-items/upload",
            post(crate::talent::upload_portfolio_item),
        )
        // Invoices (Agency Dashboard)
        .route(
            "/api/invoices",
            get(crate::invoices::list).post(crate::invoices::create),
        )
        .route(
            "/api/invoices/:id",
            get(crate::invoices::get).post(crate::invoices::update),
        )
        .route(
            "/api/invoices/:id/mark-sent",
            post(crate::invoices::mark_sent),
        )
        .route(
            "/api/invoices/:id/send-payment-reminder",
            post(crate::invoices::send_payment_reminder),
        )
        .route(
            "/api/invoices/:id/mark-paid",
            post(crate::invoices::mark_paid),
        )
        .route(
            "/api/invoices/:id/void",
            post(crate::invoices::void_invoice),
        )
        // Talent Statements (Agency Dashboard)
        .route(
            "/api/talent-statements",
            get(crate::talent_statements::list),
        )
        // Expenses (Agency Dashboard)
        .route(
            "/api/expenses",
            get(crate::expenses::list).post(crate::expenses::create),
        )
        .route("/api/kyc/session", post(crate::kyc::create_session))
        .route("/api/kyc/status", get(crate::kyc::get_status))
        .route(
            "/api/kyc/organization/session",
            post(crate::kyc::create_session),
        )
        .route("/api/kyc/organization/status", get(crate::kyc::get_status))
        // Brands
        .route("/api/brand-register", post(crate::brands::register))
        .route("/api/brand-profile", post(crate::brands::update))
        .route("/api/brand-profile/user", get(crate::brands::get_by_user))
        // Agencies
        .route("/api/agency-register", post(crate::agencies::register))
        .route("/api/agency-profile", post(crate::agencies::update))
        // Agency Dashboard
        .route(
            "/api/agency/dashboard/overview",
            get(crate::agency_dashboard::get_dashboard_overview),
        )
        .route(
            "/api/agency/dashboard/talent-performance",
            get(crate::agency_dashboard::get_talent_performance),
        )
        .route(
            "/api/agency/dashboard/revenue-breakdown",
            get(crate::agency_dashboard::get_revenue_breakdown),
        )
        .route(
            "/api/agency/dashboard/licensing-pipeline",
            get(crate::agency_dashboard::get_licensing_pipeline),
        )
        .route(
            "/api/agency/dashboard/recent-activity",
            get(crate::agency_dashboard::get_recent_activity),
        )
        .route("/api/agency/roster", get(crate::agency_roster::get_roster))
        .route(
            "/api/agency/talent-invites",
            get(crate::agency_talent_invites::list_for_agency)
                .post(crate::agency_talent_invites::create_for_agency),
        )
        .route(
            "/api/agency/talent-invites/:id/revoke",
            post(crate::agency_talent_invites::revoke_for_agency),
        )
        .route(
            "/api/agency/talent",
            post(crate::agency_roster::create_talent),
        )
        .route(
            "/api/agency/talent/:id",
            post(crate::agency_roster::update_talent),
        )
        .route(
            "/api/agency/talent/:id/campaigns",
            get(crate::agency_roster::list_talent_campaigns),
        )
        .route(
            "/api/agency/campaigns/:id",
            post(crate::campaigns::update_campaign_split),
        )
        .route(
            "/api/agency/licensing-requests",
            get(crate::licensing_requests::list_for_agency).post(crate::licensing_requests::create),
        )
        .route(
            "/api/agency/active-licenses",
            get(crate::active_licenses::list),
        )
        .route(
            "/api/agency/active-licenses/stats",
            get(crate::active_licenses::stats),
        )
        // License Templates
        .route(
            "/api/license-templates",
            get(crate::license_templates::list).post(crate::license_templates::create),
        )
        .route(
            "/api/license-templates/stats",
            get(crate::license_templates::stats),
        )
        .route(
            "/api/license-templates/:id",
            post(crate::license_templates::update)
                .delete(crate::license_templates::delete_template),
        )
        .route(
            "/api/license-templates/:id/copy",
            post(crate::license_templates::copy),
        )
        .route(
            "/api/docuseal/builder-token",
            post(crate::license_templates::create_builder_token),
        )
        // License Submissions
        .route(
            "/api/license-submissions",
            get(crate::license_submissions::list).post(crate::license_submissions::create),
        )
        .route(
            "/api/license-submissions/draft",
            post(crate::license_submissions::create_draft),
        )
        .route(
            "/api/license-submissions/create-and-send",
            post(crate::license_submissions::create_and_send),
        )
        .route(
            "/api/license-submissions/:id/finalize",
            post(crate::license_submissions::finalize),
        )
        .route(
            "/api/license-submissions/:id/preview",
            post(crate::license_submissions::preview),
        )
        .route(
            "/api/license-submissions/:id",
            get(crate::license_submissions::get).delete(crate::license_submissions::archive),
        )
        .route(
            "/api/license-submissions/:id/resend",
            post(crate::license_submissions::resend),
        )
        .route(
            "/api/license-submissions/:id/sync-status",
            post(crate::license_submissions::sync_status),
        )
        .route(
            "/api/agency/licensing-requests/status",
            post(crate::licensing_requests::update_status_bulk),
        )
        .route(
            "/api/agency/licensing-requests/:id/send-payment-link",
            post(crate::licensing_requests::send_payment_link),
        )
        .route(
            "/api/webhooks/licenseContract",
            post(crate::license_submissions::handle_webhook),
        )
        .route(
            "/api/agency/licensing-requests/pay-split",
            get(crate::licensing_requests::get_pay_split)
                .post(crate::licensing_requests::set_pay_split),
        )
        // Payment Links (for licensing)
        .route(
            "/api/agency/payment-links",
            get(crate::payment_links::list_payment_links)
                .post(crate::payment_links::generate_payment_link),
        )
        .route(
            "/api/agency/payment-links/:id",
            get(crate::payment_links::get_payment_link)
                .post(crate::payment_links::cancel_payment_link),
        )
        .route(
            "/api/agency/payment-links/send",
            post(crate::payment_links::send_payment_link_email),
        )
        // Creator Balance & Payout
        .route(
            "/api/creator/balance",
            get(crate::payment_links::get_creator_balance),
        )
        .route(
            "/api/creator/payout-request",
            post(crate::payment_links::request_creator_payout),
        )
        .route(
            "/api/creator/payout-history",
            get(crate::payment_links::get_creator_payout_history),
        )
        .route(
            "/api/agency/digitals",
            get(crate::digitals::list_agency_digitals),
        )
        .route(
            "/api/agency/talent/:id/digitals",
            get(crate::digitals::list_talent_digitals).post(crate::digitals::create_talent_digital),
        )
        .route(
            "/api/agency/digitals/:id",
            post(crate::digitals::update_digital),
        )
        .route(
            "/api/agency/digitals/reminders",
            post(crate::digitals::send_digitals_reminders),
        )
        .route(
            "/api/agency/comp-cards/share",
            post(crate::agency_clients::share_comp_card),
        )
        .route("/api/agency/talents", get(crate::agencies::list_talents))
        .route(
            "/api/agency/talents/:id/assets",
            get(crate::agencies::list_talent_assets),
        )
        .route(
            "/api/agency/talents/:id/assets/upload",
            post(crate::agencies::upload_talent_asset),
        )
        .route(
            "/api/agency/talents/:talent_id/assets/:asset_id",
            delete(crate::agencies::delete_talent_asset),
        )
        .route(
            "/api/agency/clients",
            get(crate::agencies::list_clients).post(crate::agencies::create_client),
        )
        .route(
            "/api/agency-profile/user",
            get(crate::agencies::get_profile),
        )
        .route(
            "/api/agency/clients/:id",
            post(crate::agencies::update_client).delete(crate::agencies::delete_client),
        )
        .route(
            "/api/agency/clients/:id/contacts",
            get(crate::agencies::list_contacts).post(crate::agencies::create_contact),
        )
        .route(
            "/api/agency/clients/:client_id/contacts/:contact_id",
            delete(crate::agencies::delete_contact),
        )
        .route(
            "/api/agency/clients/:id/communications",
            get(crate::agencies::list_communications).post(crate::agencies::create_communication),
        )
        // Agency Storage (S3-backed via Supabase Storage)
        .route(
            "/api/agency/storage/usage",
            get(crate::agencies::get_agency_storage_usage),
        )
        .route(
            "/api/agency/storage/folders",
            get(crate::agencies::list_agency_folders).post(crate::agencies::create_agency_folder),
        )
        .route(
            "/api/agency/storage/files",
            get(crate::agencies::list_agency_files),
        )
        .route(
            "/api/agency/storage/files/upload",
            post(crate::agencies::upload_agency_storage_file),
        )
        .route(
            "/api/agency/storage/files/:file_id",
            delete(crate::agencies::delete_agency_storage_file),
        )
        .route(
            "/api/agency/storage/files/:file_id/signed-url",
            get(crate::agencies::get_agency_storage_file_signed_url),
        )
        .route(
            "/api/agency/files/upload",
            post(crate::agencies::upload_agency_file),
        )
        .route(
            "/api/agency/clients/:id/files",
            get(crate::agencies::list_client_files).post(crate::agencies::upload_client_file),
        )
        .route(
            "/api/agency/clients/:id/files/:file_id/signed-url",
            get(crate::agencies::get_client_file_signed_url),
        )
        // Talent Packages
        .route(
            "/api/agency/packages",
            get(crate::packages::list_packages).post(crate::packages::create_package),
        )
        .route(
            "/api/agency/packages/stats",
            get(crate::packages::get_dashboard_stats),
        )
        .route(
            "/api/agency/packages/:id",
            get(crate::packages::get_package)
                .delete(crate::packages::delete_package)
                .put(crate::packages::update_package),
        )
        .route(
            "/api/public/packages/:token",
            get(crate::packages::get_public_package),
        )
        .route(
            "/api/public/packages/:token/full-assets-request",
            post(crate::packages::create_public_package_full_assets_request),
        )
        .route(
            "/api/public/packages/:token/interactions",
            post(crate::packages::create_interaction).delete(crate::packages::delete_interaction),
        )
        .route("/api/dashboard", get(crate::dashboard::get_dashboard))
        .route(
            "/api/agency/dashboard/performance-tiers",
            get(crate::performance_tiers::get_performance_tiers),
        )
        .route(
            "/api/agency/dashboard/performance-tiers/configure",
            post(crate::performance_tiers::configure_performance_tiers),
        )
        .route(
            "/api/agency/dashboard/payout-weights",
            get(crate::performance_tiers::get_agency_payout_weights),
        )
        .route("/webhooks/kyc/veriff", post(crate::kyc::veriff_webhook))
        .route("/api/email/available", get(crate::creators::check_email))
        .route("/api/profile", post(crate::creators::upsert_profile))
        .route(
            "/api/profile/photo-upload",
            post(crate::creators::upload_profile_photo),
        )
        .route(
            "/api/face-profiles",
            post(crate::face_profiles::create_face_profile),
        )
        .route(
            "/api/face-profiles/:id",
            post(crate::face_profiles::update_face_profile),
        )
        .route("/api/faces/search", get(crate::face_profiles::search_faces))
        .route(
            "/api/moderation/image",
            post(crate::moderation::moderate_image),
        )
        .route(
            "/api/moderation/image-bytes",
            post(crate::moderation::moderate_image_bytes),
        )
        .route(
            "/api/reference-images/upload",
            post(crate::reference_images::upload_reference_image),
        )
        .route(
            "/api/reference-images",
            get(crate::reference_images::list_reference_images),
        )
        .route(
            "/api/reference-images/:section_id",
            delete(crate::reference_images::delete_reference_image),
        )
        // Voice
        .route(
            "/api/voice/recordings",
            post(crate::voice::upload_voice_recording),
        )
        .route(
            "/api/voice/recordings",
            get(crate::voice::list_voice_recordings),
        )
        .route(
            "/api/voice/models",
            post(crate::voice::register_voice_model),
        )
        .route(
            "/api/voice/models/clone",
            post(crate::voice::create_clone_from_recording),
        )
        .route(
            "/api/voice/recordings/signed-url",
            get(crate::voice::signed_url_for_recording),
        )
        .route(
            "/api/voice/recordings/:id",
            delete(crate::voice::delete_voice_recording),
        )
        // Licensing activation stub (to be called by checkout flow)
        .route(
            "/api/licenses/activated",
            post(crate::licenses::activated_stub),
        )
        // Brand voice folders/assets listing (implemented in licenses module)
        .route(
            "/api/brand/voice-folders",
            get(crate::licenses::list_brand_voice_folders),
        )
        .route(
            "/api/brand/voice-assets",
            get(crate::licenses::list_brand_voice_assets),
        )
        // Bookings (Agency Dashboard)
        .route(
            "/api/bookings",
            get(crate::bookings::list).post(crate::bookings::create),
        )
        .route(
            "/api/bookings/with-files",
            post(crate::bookings::create_with_files),
        )
        .route("/api/bookings/:id", post(crate::bookings::update))
        .route(
            "/api/bookings/:id/files/upload",
            post(crate::bookings::upload_booking_file),
        )
        .route("/api/bookings/:id/cancel", post(crate::bookings::cancel))
        // Book-Outs (Availability)
        .route(
            "/api/book-outs",
            get(crate::book_outs::list).post(crate::book_outs::create),
        )
        .route(
            "/api/book-outs/:id",
            delete(crate::book_outs::delete_book_out),
        )
        // Payouts
        .route(
            "/api/payouts/onboarding_link",
            post(crate::payouts::create_onboarding_link),
        )
        .route(
            "/api/payouts/account_status",
            get(crate::payouts::get_account_status),
        )
        .route("/api/payouts/balance", get(crate::payouts::get_balance))
        .route("/api/payouts/request", post(crate::payouts::request_payout))
        .route("/api/payouts/history", get(crate::payouts::get_history))
        .route("/webhooks/stripe", post(crate::payouts::stripe_webhook))
        // Agency Stripe Connect (Accounting)
        .route(
            "/api/agency/payouts/onboarding_link",
            post(crate::payouts::create_agency_onboarding_link),
        )
        .route(
            "/api/agency/payouts/account_status",
            get(crate::payouts::get_agency_account_status),
        )
        .route(
            "/api/agency/payouts/balance",
            get(crate::payouts::get_agency_balance),
        )
        .route(
            "/api/agency/payouts/request",
            post(crate::payouts::request_agency_payout),
        )
        .route(
            "/api/agency/payouts/history",
            get(crate::payouts::get_agency_payout_history),
        )
        .route(
            "/api/agency/billing/checkout",
            post(crate::billing::create_agency_subscription_checkout),
        )
        // Integrations: Core
        .route(
            "/api/integrations/core/send-email",
            post(crate::email::send_email),
        )
        .route(
            "/api/invites/agency-talent/:token",
            get(crate::agency_talent_invites::get_by_token),
        )
        .route(
            "/api/invites/agency-talent/:token/accept",
            post(crate::agency_talent_invites::accept_by_token),
        )
        .route(
            "/api/invites/agency-talent/:token/decline",
            post(crate::agency_talent_invites::decline_by_token),
        )
        .route(
            "/api/invites/agency-talent/:token/magic-link",
            get(crate::agency_talent_invites::get_magic_link_by_token),
        )
        .route(
            "/api/creator-rates",
            get(crate::creator_rates::get_creator_rates)
                .post(crate::creator_rates::upsert_creator_rates),
        )
        // Creator: Agency Connection
        .route(
            "/api/creator/agency-invites",
            get(crate::creator_agency_connection::list_invites),
        )
        .route(
            "/api/creator/agency-invites/:id/accept",
            post(crate::creator_agency_connection::accept_invite),
        )
        .route(
            "/api/creator/agency-invites/:id/decline",
            post(crate::creator_agency_connection::decline_invite),
        )
        // Scouting (DocuSeal)
        .route(
            "/api/scouting/templates",
            get(crate::scouting::list_templates).post(crate::scouting::create_template),
        )
        .route(
            "/api/scouting/templates/sync",
            post(crate::scouting::sync_templates),
        )
        .route(
            "/api/scouting/templates/upload",
            post(crate::scouting::create_template_from_pdf),
        )
        .route(
            "/api/scouting/templates/:id",
            delete(crate::scouting::delete_template).put(crate::scouting::update_template_from_pdf),
        )
        .route(
            "/api/scouting/offers",
            get(crate::scouting::list_offers).post(crate::scouting::create_offer),
        )
        .route(
            "/api/scouting/offers/:offer_id",
            get(crate::scouting::get_offer_details).delete(crate::scouting::delete_offer),
        )
        .route(
            "/api/scouting/offers/refresh-status",
            post(crate::scouting::refresh_offer_status),
        )
        .route("/api/scouting/geocode", get(crate::scouting::geocode))
        .route(
            "/api/scouting/builder-token",
            post(crate::scouting::create_builder_token),
        )
        .route("/webhooks/docuseal", post(crate::scouting::handle_webhook))
        // Notifications
        .route(
            "/api/notifications/booking-created-email",
            post(crate::notifications::booking_created_email),
        )
        .route(
            "/api/notifications/booking-notifications",
            get(crate::notifications::list_booking_notifications),
        )
        .with_state(state)
        .layer(DefaultBodyLimit::max(20_000_000)) // 20MB limit
        .layer(cors)
}
